"""empty message

Revision ID: 3fc82e04dc87
Revises: 9157eeb6d8c3
Create Date: 2025-08-15 11:04:44.572855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc82e04dc87'
down_revision: Union[str, Sequence[str], None] = '9157eeb6d8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
